version: "3"
networks:
  indexer_net:
    external: false

services:
  database:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    networks:
     - indexer_net
    env_file:
     - database.env    
    volumes:
     - db-data:/var/lib/postgresql/data/
    ports:
     - 5432:5432
  indexer:
    depends_on:
      - database
    networks:
      - indexer_net
    build:
      context: .
      dockerfile: Dockerfile
  api:
    depends_on:
      - database
    networks:
      - indexer_net
    ports:
      - 80:80
      - 443:443
    build:
      context: .
      dockerfile: WebApi/Dockerfile
  ui:
    depends_on:
      - api
    networks:
      - indexer_net
    ports:
      - 4200:80
    build:
      context: ./polkascan-pre-explorer-gui
      dockerfile: Dockerfile
          
volumes:
  db-data:
